services:
  - type: web
    name: finance-rag-backend
    env: python
    region: oregon
    runtime: python-3.11.8 
    buildCommand: pip install -r server/requirements.txt
    startCommand: python server/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        value: neo4j
      - key: NEO4J_PASSWORD
        sync: false
      - key: NEO4J_DATABASE
        value: neo4j
      - key: ALPHA_VANTAGE_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: OPENROUTER_GEMMA_API_KEY
        sync: false
    plan: free
    disk:
      name: flask-app-disk
      mountPath: /app/data
      sizeGB: 1
